# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_subject.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_new_subject(object):
    def setupUi(self, dialog_new_subject):
        dialog_new_subject.setObjectName("dialog_new_subject")
        dialog_new_subject.resize(475, 200)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setItalic(False)
        dialog_new_subject.setFont(font)
        dialog_new_subject.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.layoutWidget = QtWidgets.QWidget(dialog_new_subject)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 451, 177))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vert_layout_new_subject = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vert_layout_new_subject.setContentsMargins(0, 0, 0, 0)
        self.vert_layout_new_subject.setObjectName("vert_layout_new_subject")
        self.lbl_new_subject = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_new_subject.setFont(font)
        self.lbl_new_subject.setObjectName("lbl_new_subject")
        self.vert_layout_new_subject.addWidget(self.lbl_new_subject)
        self.hori_line_new_subject = QtWidgets.QFrame(self.layoutWidget)
        self.hori_line_new_subject.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_new_subject.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_new_subject.setObjectName("hori_line_new_subject")
        self.vert_layout_new_subject.addWidget(self.hori_line_new_subject)
        self.hori_layout_subject = QtWidgets.QHBoxLayout()
        self.hori_layout_subject.setObjectName("hori_layout_subject")
        self.lbl_subject_name = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_subject_name.setObjectName("lbl_subject_name")
        self.hori_layout_subject.addWidget(self.lbl_subject_name)
        self.line_edit_subject_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_edit_subject_name.setObjectName("line_edit_subject_name")
        self.hori_layout_subject.addWidget(self.line_edit_subject_name)
        self.vert_layout_new_subject.addLayout(self.hori_layout_subject)
        self.hori_line_subject = QtWidgets.QFrame(self.layoutWidget)
        self.hori_line_subject.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_subject.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_subject.setObjectName("hori_line_subject")
        self.vert_layout_new_subject.addWidget(self.hori_line_subject)
        self.lbl_instruction = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.lbl_instruction.setFont(font)
        self.lbl_instruction.setObjectName("lbl_instruction")
        self.vert_layout_new_subject.addWidget(self.lbl_instruction, 0, QtCore.Qt.AlignVCenter)
        self.button_box_new_subject = QtWidgets.QDialogButtonBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setItalic(False)
        self.button_box_new_subject.setFont(font)
        self.button_box_new_subject.setOrientation(QtCore.Qt.Horizontal)
        self.button_box_new_subject.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.button_box_new_subject.setObjectName("button_box_new_subject")
        self.vert_layout_new_subject.addWidget(self.button_box_new_subject, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)

        self.retranslateUi(dialog_new_subject)
        self.button_box_new_subject.rejected.connect(dialog_new_subject.reject)
        self.button_box_new_subject.accepted.connect(dialog_new_subject.accept)
        QtCore.QMetaObject.connectSlotsByName(dialog_new_subject)

    def retranslateUi(self, dialog_new_subject):
        _translate = QtCore.QCoreApplication.translate
        dialog_new_subject.setWindowTitle(_translate("dialog_new_subject", "Add Subject"))
        self.lbl_new_subject.setText(_translate("dialog_new_subject", "Add a New Subject"))
        self.lbl_subject_name.setText(_translate("dialog_new_subject", "Subject Name:"))
        self.lbl_instruction.setText(_translate("dialog_new_subject", "Please enter your subject name (maximum 30 characters)."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_new_subject = QtWidgets.QDialog()
    ui = Ui_dialog_new_subject()
    ui.setupUi(dialog_new_subject)
    dialog_new_subject.show()
    sys.exit(app.exec_())
