# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student_planner.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mwindow_menu(object):
    def setupUi(self, mwindow_menu):
        mwindow_menu.setObjectName("mwindow_menu")
        mwindow_menu.resize(500, 170)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        mwindow_menu.setFont(font)
        self.central_widget = QtWidgets.QWidget(mwindow_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.central_widget.sizePolicy().hasHeightForWidth())
        self.central_widget.setSizePolicy(sizePolicy)
        self.central_widget.setObjectName("central_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.central_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.vert_layout_menu = QtWidgets.QVBoxLayout()
        self.vert_layout_menu.setObjectName("vert_layout_menu")
        self.lbl_menu = QtWidgets.QLabel(self.central_widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_menu.setFont(font)
        self.lbl_menu.setObjectName("lbl_menu")
        self.vert_layout_menu.addWidget(self.lbl_menu)
        self.hori_line_header = QtWidgets.QFrame(self.central_widget)
        self.hori_line_header.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_header.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_header.setObjectName("hori_line_header")
        self.vert_layout_menu.addWidget(self.hori_line_header)
        self.hori_layout_nav = QtWidgets.QHBoxLayout()
        self.hori_layout_nav.setObjectName("hori_layout_nav")
        self.btn_my_subjects = QtWidgets.QPushButton(self.central_widget)
        self.btn_my_subjects.setObjectName("btn_my_subjects")
        self.hori_layout_nav.addWidget(self.btn_my_subjects, 0, QtCore.Qt.AlignLeft)
        self.line = QtWidgets.QFrame(self.central_widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hori_layout_nav.addWidget(self.line)
        self.btn_agenda = QtWidgets.QPushButton(self.central_widget)
        self.btn_agenda.setObjectName("btn_agenda")
        self.hori_layout_nav.addWidget(self.btn_agenda)
        self.btn_timetable = QtWidgets.QPushButton(self.central_widget)
        self.btn_timetable.setObjectName("btn_timetable")
        self.hori_layout_nav.addWidget(self.btn_timetable)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hori_layout_nav.addItem(spacerItem)
        self.vert_layout_menu.addLayout(self.hori_layout_nav)
        self.hori_line_nav = QtWidgets.QFrame(self.central_widget)
        self.hori_line_nav.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_nav.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_nav.setObjectName("hori_line_nav")
        self.vert_layout_menu.addWidget(self.hori_line_nav)
        self.lbl_instruction = QtWidgets.QLabel(self.central_widget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.lbl_instruction.setFont(font)
        self.lbl_instruction.setTextFormat(QtCore.Qt.RichText)
        self.lbl_instruction.setWordWrap(True)
        self.lbl_instruction.setObjectName("lbl_instruction")
        self.vert_layout_menu.addWidget(self.lbl_instruction)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vert_layout_menu.addItem(spacerItem1)
        self.gridLayout.addLayout(self.vert_layout_menu, 0, 0, 1, 1)
        mwindow_menu.setCentralWidget(self.central_widget)

        self.retranslateUi(mwindow_menu)
        QtCore.QMetaObject.connectSlotsByName(mwindow_menu)

    def retranslateUi(self, mwindow_menu):
        _translate = QtCore.QCoreApplication.translate
        mwindow_menu.setWindowTitle(_translate("mwindow_menu", "Main Menu - Student Planner"))
        self.lbl_menu.setText(_translate("mwindow_menu", "Student Planner - Main Menu"))
        self.btn_my_subjects.setText(_translate("mwindow_menu", "My Subjects"))
        self.btn_agenda.setText(_translate("mwindow_menu", "Agenda"))
        self.btn_timetable.setText(_translate("mwindow_menu", "Timetable"))
        self.lbl_instruction.setText(_translate("mwindow_menu", "To enable full functionality in the agenda and timetable, please ensure you have entered all of your subjects in My Subjects."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mwindow_menu = QtWidgets.QMainWindow()
    ui = Ui_mwindow_menu()
    ui.setupUi(mwindow_menu)
    mwindow_menu.show()
    sys.exit(app.exec_())
