# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_timetable.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_edit_timetable(object):
    def setupUi(self, dialog_edit_timetable):
        dialog_edit_timetable.setObjectName("dialog_edit_timetable")
        dialog_edit_timetable.resize(725, 260)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        dialog_edit_timetable.setFont(font)
        self.layoutWidget = QtWidgets.QWidget(dialog_edit_timetable)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 701, 235))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vert_layout_edit_timetable = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vert_layout_edit_timetable.setContentsMargins(0, 0, 0, 0)
        self.vert_layout_edit_timetable.setObjectName("vert_layout_edit_timetable")
        self.lbl_edit_timetable = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_edit_timetable.setFont(font)
        self.lbl_edit_timetable.setObjectName("lbl_edit_timetable")
        self.vert_layout_edit_timetable.addWidget(self.lbl_edit_timetable)
        self.hori_line_edit_timetable = QtWidgets.QFrame(self.layoutWidget)
        self.hori_line_edit_timetable.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_edit_timetable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_edit_timetable.setObjectName("hori_line_edit_timetable")
        self.vert_layout_edit_timetable.addWidget(self.hori_line_edit_timetable)
        self.form_layout_edit_timetable = QtWidgets.QFormLayout()
        self.form_layout_edit_timetable.setObjectName("form_layout_edit_timetable")
        self.lbl_subject = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_subject.setObjectName("lbl_subject")
        self.form_layout_edit_timetable.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_subject)
        self.comb_box_subject = QtWidgets.QComboBox(self.layoutWidget)
        self.comb_box_subject.setFrame(True)
        self.comb_box_subject.setObjectName("comb_box_subject")
        self.form_layout_edit_timetable.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comb_box_subject)
        self.lbl_teacher = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_teacher.setObjectName("lbl_teacher")
        self.form_layout_edit_timetable.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_teacher)
        self.line_edit_teacher = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_edit_teacher.setObjectName("line_edit_teacher")
        self.form_layout_edit_timetable.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_edit_teacher)
        self.lbl_room = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_room.setObjectName("lbl_room")
        self.form_layout_edit_timetable.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_room)
        self.line_edit_room = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_edit_room.setObjectName("line_edit_room")
        self.form_layout_edit_timetable.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_edit_room)
        self.vert_layout_edit_timetable.addLayout(self.form_layout_edit_timetable)
        self.hori_line_lesson_details = QtWidgets.QFrame(self.layoutWidget)
        self.hori_line_lesson_details.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_lesson_details.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_lesson_details.setObjectName("hori_line_lesson_details")
        self.vert_layout_edit_timetable.addWidget(self.hori_line_lesson_details)
        self.lbl_instruction = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.lbl_instruction.setFont(font)
        self.lbl_instruction.setObjectName("lbl_instruction")
        self.vert_layout_edit_timetable.addWidget(self.lbl_instruction)
        self.button_box_edit_timetable = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.button_box_edit_timetable.setOrientation(QtCore.Qt.Horizontal)
        self.button_box_edit_timetable.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.button_box_edit_timetable.setObjectName("button_box_edit_timetable")
        self.vert_layout_edit_timetable.addWidget(self.button_box_edit_timetable, 0, QtCore.Qt.AlignLeft)

        self.retranslateUi(dialog_edit_timetable)
        self.button_box_edit_timetable.accepted.connect(dialog_edit_timetable.accept)
        self.button_box_edit_timetable.rejected.connect(dialog_edit_timetable.reject)
        QtCore.QMetaObject.connectSlotsByName(dialog_edit_timetable)

    def retranslateUi(self, dialog_edit_timetable):
        _translate = QtCore.QCoreApplication.translate
        dialog_edit_timetable.setWindowTitle(_translate("dialog_edit_timetable", "Edit Timetable Slot"))
        self.lbl_edit_timetable.setText(_translate("dialog_edit_timetable", "Edit Timetable Slot"))
        self.lbl_subject.setText(_translate("dialog_edit_timetable", "Subject:"))
        self.lbl_teacher.setText(_translate("dialog_edit_timetable", "Teacher:"))
        self.lbl_room.setText(_translate("dialog_edit_timetable", "Room:"))
        self.lbl_instruction.setText(_translate("dialog_edit_timetable", "Please select a subject, and optionally a teacher and room (maximum 30 and 20 characters)."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_edit_timetable = QtWidgets.QDialog()
    ui = Ui_dialog_edit_timetable()
    ui.setupUi(dialog_edit_timetable)
    dialog_edit_timetable.show()
    sys.exit(app.exec_())
