# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_task.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_new_task(object):
    def setupUi(self, dialog_new_task):
        dialog_new_task.setObjectName("dialog_new_task")
        dialog_new_task.resize(600, 460)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        dialog_new_task.setFont(font)
        self.layoutWidget = QtWidgets.QWidget(dialog_new_task)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 571, 433))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vert_layout_new_task = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vert_layout_new_task.setContentsMargins(0, 0, 0, 0)
        self.vert_layout_new_task.setObjectName("vert_layout_new_task")
        self.lbl_new_task = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_new_task.setFont(font)
        self.lbl_new_task.setObjectName("lbl_new_task")
        self.vert_layout_new_task.addWidget(self.lbl_new_task)
        self.hori_line_new_task = QtWidgets.QFrame(self.layoutWidget)
        self.hori_line_new_task.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_new_task.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_new_task.setObjectName("hori_line_new_task")
        self.vert_layout_new_task.addWidget(self.hori_line_new_task)
        self.form_layout_task_details = QtWidgets.QFormLayout()
        self.form_layout_task_details.setObjectName("form_layout_task_details")
        self.lbl_task_title = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_task_title.setObjectName("lbl_task_title")
        self.form_layout_task_details.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_task_title)
        self.line_edit_task_title = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_edit_task_title.setObjectName("line_edit_task_title")
        self.form_layout_task_details.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_edit_task_title)
        self.lbl_subject = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_subject.setObjectName("lbl_subject")
        self.form_layout_task_details.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_subject)
        self.comb_box_subject = QtWidgets.QComboBox(self.layoutWidget)
        self.comb_box_subject.setFrame(True)
        self.comb_box_subject.setObjectName("comb_box_subject")
        self.form_layout_task_details.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comb_box_subject)
        self.lbl_due_date = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_due_date.setObjectName("lbl_due_date")
        self.form_layout_task_details.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_due_date)
        self.calendar_due_date = QtWidgets.QCalendarWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendar_due_date.sizePolicy().hasHeightForWidth())
        self.calendar_due_date.setSizePolicy(sizePolicy)
        self.calendar_due_date.setObjectName("calendar_due_date")
        self.form_layout_task_details.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.calendar_due_date)
        self.vert_layout_new_task.addLayout(self.form_layout_task_details)
        self.hori_line_task_details = QtWidgets.QFrame(self.layoutWidget)
        self.hori_line_task_details.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_task_details.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_task_details.setObjectName("hori_line_task_details")
        self.vert_layout_new_task.addWidget(self.hori_line_task_details)
        self.lbl_instruction = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.lbl_instruction.setFont(font)
        self.lbl_instruction.setObjectName("lbl_instruction")
        self.vert_layout_new_task.addWidget(self.lbl_instruction)
        self.button_box_new_task = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.button_box_new_task.setOrientation(QtCore.Qt.Horizontal)
        self.button_box_new_task.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.button_box_new_task.setObjectName("button_box_new_task")
        self.vert_layout_new_task.addWidget(self.button_box_new_task, 0, QtCore.Qt.AlignLeft)

        self.retranslateUi(dialog_new_task)
        self.button_box_new_task.rejected.connect(dialog_new_task.reject)
        self.button_box_new_task.accepted.connect(dialog_new_task.accept)
        QtCore.QMetaObject.connectSlotsByName(dialog_new_task)

    def retranslateUi(self, dialog_new_task):
        _translate = QtCore.QCoreApplication.translate
        dialog_new_task.setWindowTitle(_translate("dialog_new_task", "Add Task"))
        self.lbl_new_task.setText(_translate("dialog_new_task", "Add a New Task"))
        self.lbl_task_title.setText(_translate("dialog_new_task", "Task Title:"))
        self.lbl_subject.setText(_translate("dialog_new_task", "Subject:"))
        self.lbl_due_date.setText(_translate("dialog_new_task", "Due Date:"))
        self.lbl_instruction.setText(_translate("dialog_new_task", "Please enter a task title (maximum 30 characters), subject, and due date."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_new_task = QtWidgets.QDialog()
    ui = Ui_dialog_new_task()
    ui.setupUi(dialog_new_task)
    dialog_new_task.show()
    sys.exit(app.exec_())
